---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - nginx
        - mariadb-server
        - php5
        - php5-fpm
    - name: configure nginx
      template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf
      template: src=templates/default dest=/etc/nginx/sites-available/default
    - name: reload nginx
      service: name=nginx state=reloaded
